version: '3.1'
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 9527:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./react-auto/build:/var/www/html/
      - ./static/:/static/
  app-pm2:
    container_name: app-pm2 #构建容器
    build: ./koa-auto
    ports:
      - 3000:3000
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017